# Generated by Django 5.2 on 2025-04-22 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_data', '0004_processdetail'),
        ('productionmgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderProcessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveIntegerField(verbose_name='工序号')),
                ('machine_time', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='设备时间(分钟)')),
                ('labor_time', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='人工时间(分钟)')),
                ('program_file', models.FileField(blank=True, null=True, upload_to='programs/', verbose_name='程序文件')),
                ('status', models.CharField(default='pending', max_length=20, verbose_name='状态')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('process_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.processcode', verbose_name='工艺流程代码')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.process', verbose_name='工序名')),
                ('workorder_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_details', to='productionmgmt.workorderdetail', verbose_name='工单明细')),
            ],
            options={
                'verbose_name': '工单工艺明细',
                'verbose_name_plural': '工单工艺明细',
                'unique_together': {('workorder_detail', 'step_no')},
            },
        ),
    ]
