# Generated by Django 5.2 on 2025-05-08 05:20

import basedata.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='公司名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='公司代码')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='地址')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='联系电话')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='工序名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='工序代码')),
                ('description', models.TextField(blank=True, verbose_name='工序描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工序',
                'verbose_name_plural': '工序',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='产品代码')),
                ('name', models.CharField(max_length=40, verbose_name='产品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('drawing_pdf', models.FileField(blank=True, null=True, upload_to=basedata.models.product_pdf_upload_to, verbose_name='图纸PDF')),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
            ],
            options={
                'verbose_name': '客户',
                'verbose_name_plural': '客户',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('basedata.company',),
        ),
        migrations.CreateModel(
            name='ProcessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='工艺流程代码')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('version', models.CharField(max_length=20, verbose_name='版本')),
                ('process_pdf', models.FileField(blank=True, null=True, upload_to=basedata.models.process_pdf_upload_to, verbose_name='工艺PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工艺流程代码',
                'verbose_name_plural': '工艺流程代码',
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='BOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='BOM名称')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='版本')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='basedata.product', verbose_name='所属产品')),
            ],
            options={
                'verbose_name': 'BOM',
                'verbose_name_plural': 'BOM',
                'unique_together': {('product', 'name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
            ],
            options={
                'verbose_name': '物料',
                'verbose_name_plural': '物料',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('basedata.product',),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='产品类名称')),
                ('drawing_pdf', models.FileField(blank=True, null=True, upload_to=basedata.models.category_pdf_upload_to, verbose_name='图纸PDF')),
                ('process_pdf', models.FileField(blank=True, null=True, upload_to=basedata.models.category_process_pdf_upload_to, verbose_name='工艺PDF')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.company', verbose_name='公司')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.productcategory', verbose_name='所属产品类'),
        ),
        migrations.CreateModel(
            name='CategoryParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='参数项名称')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='basedata.productcategory')),
            ],
            options={
                'verbose_name': '参数项',
                'verbose_name_plural': '参数项',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductParamValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='参数值')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.categoryparam')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_values', to='basedata.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveIntegerField(verbose_name='工序号')),
                ('machine_time', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='设备时间(分钟)')),
                ('labor_time', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='人工时间(分钟)')),
                ('program_file', models.FileField(blank=True, null=True, upload_to='programs/', verbose_name='程序文件')),
                ('process_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='basedata.processcode', verbose_name='工艺流程代码')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.process', verbose_name='工序名')),
            ],
            options={
                'verbose_name': '工艺流程明细',
                'verbose_name_plural': '工艺流程明细',
                'unique_together': {('process_code', 'step_no')},
            },
        ),
        migrations.CreateModel(
            name='BOMItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='用量')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='basedata.bom', verbose_name='所属BOM')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_material_in_bom', to='basedata.product', verbose_name='物料')),
            ],
            options={
                'verbose_name': 'BOM明细',
                'verbose_name_plural': 'BOM明细',
                'unique_together': {('bom', 'material')},
            },
        ),
        migrations.CreateModel(
            name='ProductProcessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('process_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.processcode', verbose_name='工艺流程代码')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basedata.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品-工艺流程代码关系',
                'verbose_name_plural': '产品-工艺流程代码关系',
                'unique_together': {('product', 'process_code')},
            },
        ),
    ]
