# Generated by Django 5.2 on 2025-05-08 08:45

from django.db import migrations, models

def update_existing_products(apps, schema_editor):
    Product = apps.get_model('basedata', 'Product')
    Material = apps.get_model('basedata', 'Material')
    
    # Get all materials IDs
    material_pks = set(Material.objects.values_list('pk', flat=True))
    
    # Update all products - mark materials as True
    Product.objects.filter(pk__in=material_pks).update(is_material=True)
    
    # Mark all other products as False
    Product.objects.exclude(pk__in=material_pks).update(is_material=False)

class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_material',
            field=models.BooleanField(default=False, verbose_name='是否为外购件'),
        ),
        migrations.RunPython(update_existing_products, migrations.RunPython.noop),
    ]
