# Generated by Django 5.2 on 2025-05-12 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productparamvalue',
            options={'verbose_name': '产品参数值', 'verbose_name_plural': '产品参数值'},
        ),
        migrations.AlterUniqueTogether(
            name='productparamvalue',
            unique_together={('product', 'param')},
        ),
    ]
