# Generated by Django 5.2 on 2025-05-12 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0002_alter_productparamvalue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basedata.unit', verbose_name='默认单位'),
        ),
    ]
