# Generated by Django 5.2 on 2025-05-08 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0002_product_is_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomitem',
            name='material',
            field=models.ForeignKey(limit_choices_to={'is_material': True}, on_delete=django.db.models.deletion.CASCADE, related_name='as_material_in_bom', to='basedata.product', verbose_name='物料'),
        ),
    ]
