# Generated by Django 5.2 on 2025-05-09 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0003_alter_bomitem_material'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': '产品类', 'verbose_name_plural': '产品类'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='code',
            field=models.CharField(default='', max_length=20, verbose_name='产品类代码'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='display_name',
            field=models.CharField(default='', max_length=40, verbose_name='产品类名称'),
        ),
        # Add data migration to copy name to code and display_name
        migrations.RunSQL(
            sql="UPDATE basedata_productcategory SET code = name, display_name = name",
            reverse_sql="",
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('code', 'company')},
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='name',
        ),
    ]
