# Generated by Django 5.2 on 2025-05-09 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0004_alter_productcategory_options_and_more'),
    ]

    operations = [
    ]
