# Generated by Django 5.2 on 2025-05-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0005_merge_20250509_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='code',
            field=models.CharField(max_length=20, verbose_name='产品类代码'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='display_name',
            field=models.CharField(max_length=40, verbose_name='产品类名称'),
        ),
    ]
