# Generated by Django 5.2 on 2025-05-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basedata', '0006_alter_productcategory_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='产品名称'),
        ),
    ]
