# Generated by Django 5.2 on 2025-04-20 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30, unique=True, verbose_name='订单号')),
                ('order_date', models.DateField(verbose_name='下单日期')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='订单金额合计')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.company', verbose_name='公司')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_no', models.IntegerField(verbose_name='订单项')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='单价')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额小计')),
                ('plan_delivery', models.DateField(verbose_name='计划交货期')),
                ('actual_delivery', models.DateField(blank=True, null=True, verbose_name='实际交货期')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='实际交货数量')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='实际交货金额')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='salesmgmt.order', verbose_name='订单号')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.product', verbose_name='产品')),
            ],
        ),
    ]
