# Generated by Django 5.2 on 2025-04-21 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesmgmt', '0002_order_created_at_order_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='订单金额合计'),
        ),
    ]
