# Generated by Django 5.2 on 2025-04-25 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_data', '0001_initial'),
        ('salesmgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workorder_no', models.CharField(max_length=30, unique=True, verbose_name='工单号')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('plan_start', models.DateTimeField(blank=True, null=True, verbose_name='计划开始时间')),
                ('plan_end', models.DateTimeField(blank=True, null=True, verbose_name='计划结束时间')),
                ('actual_start', models.DateTimeField(blank=True, null=True, verbose_name='实际开始时间')),
                ('actual_end', models.DateTimeField(blank=True, null=True, verbose_name='实际结束时间')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('released', '已下达'), ('in_progress', '生产中'), ('completed', '已完成'), ('cancelled', '已取消')], default='draft', max_length=20, verbose_name='状态')),
                ('remark', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salesmgmt.order', verbose_name='订单号')),
                ('process_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base_data.processcode', verbose_name='工艺流程代码')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base_data.product', verbose_name='产品')),
            ],
        ),
    ]
