# Generated by Django 5.2 on 2025-04-25 03:34

import base_data.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='公司名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='公司代码')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='地址')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='联系电话')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='工序名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='工序代码')),
                ('description', models.TextField(blank=True, verbose_name='工序描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工序',
                'verbose_name_plural': '工序',
            },
        ),
        migrations.CreateModel(
            name='ProcessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='工艺流程代码')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('version', models.CharField(max_length=20, verbose_name='版本')),
                ('process_pdf', models.FileField(blank=True, null=True, upload_to=base_data.models.process_pdf_upload_to, verbose_name='工艺PDF')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工艺流程代码',
                'verbose_name_plural': '工艺流程代码',
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='产品类名称')),
                ('drawing_pdf', models.FileField(blank=True, null=True, upload_to=base_data.models.category_pdf_upload_to, verbose_name='图纸PDF')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.company', verbose_name='公司')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='产品代码')),
                ('name', models.CharField(max_length=40, verbose_name='产品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('drawing_pdf', models.FileField(blank=True, null=True, upload_to=base_data.models.product_pdf_upload_to, verbose_name='图纸PDF')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.productcategory', verbose_name='所属产品类')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='参数项名称')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='base_data.productcategory')),
            ],
            options={
                'verbose_name': '参数项',
                'verbose_name_plural': '参数项',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductParamValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='参数值')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.categoryparam')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_values', to='base_data.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProcessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveIntegerField(verbose_name='工序号')),
                ('machine_time', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='设备时间(分钟)')),
                ('labor_time', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='人工时间(分钟)')),
                ('program_file', models.FileField(blank=True, null=True, upload_to='programs/', verbose_name='程序文件')),
                ('process_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='base_data.processcode', verbose_name='工艺流程代码')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.process', verbose_name='工序名')),
            ],
            options={
                'verbose_name': '工艺流程明细',
                'verbose_name_plural': '工艺流程明细',
                'unique_together': {('process_code', 'step_no')},
            },
        ),
        migrations.CreateModel(
            name='ProductProcessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('process_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.processcode', verbose_name='工艺流程代码')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品-工艺流程代码关系',
                'verbose_name_plural': '产品-工艺流程代码关系',
                'unique_together': {('product', 'process_code')},
            },
        ),
    ]
