# Generated by Django 5.2 on 2025-04-20 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='公司名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='公司代码')),
                ('address', models.CharField(blank=True, max_length=100, verbose_name='地址')),
                ('contact', models.CharField(blank=True, max_length=50, verbose_name='联系人')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='联系电话')),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='产品类名称')),
                ('drawing_pdf', models.FileField(blank=True, null=True, upload_to='drawings/', verbose_name='图纸PDF')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.company', verbose_name='公司')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='产品代码')),
                ('name', models.CharField(max_length=40, verbose_name='产品名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='价格')),
                ('drawing_pdf', models.FileField(blank=True, null=True, upload_to='drawings/', verbose_name='图纸PDF')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.productcategory', verbose_name='所属产品类')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryParam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='参数项名称')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='base_data.productcategory')),
            ],
            options={
                'verbose_name': '参数项',
                'verbose_name_plural': '参数项',
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ProductParamValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=200, verbose_name='参数值')),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.categoryparam')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='param_values', to='base_data.product')),
            ],
        ),
    ]
