# Generated by Django 5.2 on 2025-04-21 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='工序名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='工序代码')),
                ('description', models.TextField(blank=True, verbose_name='工序描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工序',
                'verbose_name_plural': '工序',
            },
        ),
    ]
