# Generated by Django 5.2 on 2025-04-21 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_data', '0002_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, verbose_name='工艺流程代码')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('version', models.CharField(max_length=20, verbose_name='版本')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工艺流程代码',
                'verbose_name_plural': '工艺流程代码',
                'unique_together': {('code', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ProductProcessCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认')),
                ('process_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.processcode', verbose_name='工艺流程代码')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.product', verbose_name='产品')),
            ],
            options={
                'verbose_name': '产品-工艺流程代码关系',
                'verbose_name_plural': '产品-工艺流程代码关系',
                'unique_together': {('product', 'process_code')},
            },
        ),
    ]
