# Generated by Django 5.2 on 2025-04-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_data', '0002_productcategory_drawing_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='drawing_pdf',
            field=models.FileField(blank=True, null=True, upload_to='drawings/', verbose_name='图纸PDF'),
        ),
    ]
