# Generated by Django 5.2 on 2025-04-22 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_data', '0003_processcode_productprocesscode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_no', models.PositiveIntegerField(verbose_name='工序号')),
                ('machine_time', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='设备时间(分钟)')),
                ('labor_time', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='人工时间(分钟)')),
                ('program_file', models.FileField(blank=True, null=True, upload_to='programs/', verbose_name='程序文件')),
                ('process_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='base_data.processcode', verbose_name='工艺流程代码')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_data.process', verbose_name='工序名')),
            ],
            options={
                'verbose_name': '工艺流程明细',
                'verbose_name_plural': '工艺流程明细',
                'unique_together': {('process_code', 'step_no')},
            },
        ),
    ]
